# To run:
# 1. Edit config.env
# 2. docker-compose up --env-file=config.env

version: "3.9"

services:

  elasticsearch-pubmed:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-pubmed:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: "bridge"

  elasticsearch-pubmed-update-daemon:
    build: .
    image: elasticsearch-pubmed-update-daemon:1.0
    volumes:
      - ${PUBMED_XML_DIRECTORY}:/data
    depends_on:
      - elasticsearch-pubmed
    environment:
      - REBUILD_DELAY
    network_mode: "bridge"

#  medline-graph:
#    image: neo4j:3.5.3
#    ports: 
#      - 7474:7474
#      - 7687:7687
#    environment:
#      - NEO4J_dbms_memory_pagecache_size=1G
#      - NEO4J_dbms.memory.heap.initial_size=1G
#      - NEO4J_dbms_memory_heap_max_size=1G
#    volumes:
#      - ./graph/conf:/conf
#      - ./graph/data:/data
#      - ./graph/import:/import
#      - ./graph/logs:/logs
#      - ./graph/plugins:/plugins
#    networks:
#      - medline


volumes:
  elasticsearch-pubmed:
    external: true
